### PR TITLE
Added UltraYome Option

### PR DESCRIPTION
**Pull request by barebones3d**
Hi Bruce,
     I updated the yome-widget so it would have the option for the new UltraYome. It's still got some bugs in it that I'll hopefully figure out at some point. The biggest issue currently is that if someone selects UltraYome, then goes to a size other than OctaYome it won't show the mutually exclusive options. I was able to get it to work by binding it to an onclick event, but couldn't figure out how to uncheck the UltraYome option when the YomeSize option changed.
     They need the option up on the website though so I'm going to go with what I've got at the moment. Thanks for your help on getting me started with this. I really should have listened when your blog said to go through the ClosureScript Tutorial first...

Thanks,
     Brandon

P.S. It's pretty cool seeing your name all over the figwheel plugin when I was having to google around for answers.

### CODE REVIEW

**Comment by bhauman** [comment]
Hey Brandon!

Do you have the permissions to merge these pull requests?

I'm happy to merge them both if you are ready for me to do that.

**Comment by bhauman** [comment]
Sorry this is done in such a difficult dialect ...

**Comment by barebones3d** [comment]
Thanks Bruce,
     I have the permissions now.  I seem to have broken the feature where
it grabs the prices from the WordPress site. I don't know if that had to do
with the warning I was getting when I compiled about the uuid already
referring to cljs.core rather than congnitec.transit, etc., or that the
comment in wordpress said to change nothing other than prices. Either way
the prices are correct for now.
     No worries on the dialect.  That was actually one of the more
interesting computer projects I've had in a while. Thanks again for your
help. Sorry I went off radar for several months before getting to it.

**Comment by bhauman** [comment]
I'm glad you were able to figure it out.  Om is a little less intuitive than some other frameworks. It would be pretty straight forward to translate this to JavaScript if you need to. As the logic is fairly separate from the display.

Its really good to hear from you. Please tell Peter I say hi!

**Pull request merged**
